name: Auto-update README timestamp

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC (8h Paris)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace {{TIMESTAMP}} in README.md
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/{{TIMESTAMP}}/${TIMESTAMP}/g" README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/Fascinax/Fascinax.git
          git add README.md
          git commit -m "Update README timestamp - $(date +%s)"
          git push
