name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # toutes les 12h
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Fascinax
          show_icons: true
          hide_border: true
          cache_seconds: 7200  # facultatif
